version: "3.3"

secrets:
  cert.pem:
    file: nginx/cert.pem
  key.pem:
    file: nginx/key.pem
  aws_creds:
    file: .aws/credentials

services:
  explodinator-api:
    image: bibilthaysose/explodinator-api
    secrets:
      - aws_creds
    ports:
      - "8080"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  explodinator-proxy:
    image: bibilthaysose/explodinator-proxy
    network_mode: "service:explodinator-api"
    environment:
      NODE_ENV: ${NODE_ENV}
    secrets:
      - cert.pem
      - key.pem
    ports:
      - "443:443"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
