version: "3.3"

secrets:
  aws_creds:
    file: .aws/credentials

volumes:
  mongo-1-data:
  mongo-2-data:
  mongo-3-data:

networks:
  luzene:
    external: true

services:
  mongo-1:
    image: mongo:3.4
    command: ["mongod", "--replSet", "exploderSet"]
    ports:
      - 27017
    networks:
      - default
    deploy:
      placement:
        constraints: [node.hostname==explodinator-1]
    volumes:
      - mongo-1-data:/data/db
  mongo-2:
    image: mongo:3.4
    command: ["mongod", "--replSet", "exploderSet"]
    networks:
      - default
    ports:
      - 27017
    deploy:
      placement:
        constraints: [node.hostname==explodinator-2]
    volumes:
      - mongo-2-data:/data/db
  mongo-3:
    image: mongo:3.4
    command: ["mongod", "--replSet", "exploderSet"]
    ports:
      - 27017
    networks:
      - default
    deploy:
      placement:
        constraints: [node.hostname==explodinator-3]
    volumes:
      - mongo-3-data:/data/db
  explodinator-api:
    image: bibilthaysose/explodinator-api
    environment:
      MONGODB_HOST: mongo-1
    secrets:
      - aws_creds
    ports:
      - 8080
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname==explodinator-1]
      restart_policy:
        condition: on-failure
  explodinator-proxy:
    image: bibilthaysose/explodinator-proxy
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - default
      - luzene
    ports:
      - "80"
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname==explodinator-1]
      restart_policy:
        condition: on-failure
