version: "3.3"

secrets:
  cert.pem:
    file: nginx/cert.pem
  key.pem:
    file: nginx/key.pem
  aws_creds:
    file: .aws/credentials

services:
  explodinator-api:
    image: bibilthaysose/explodinator-api
    secrets:
      - aws_creds
    networks:
      backend:
        aliases:
          - explodinator-api
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  explodinator-proxy:
    image: bibilthaysose/explodinator-proxy
    environment:
      NODE_ENV: ${NODE_ENV}
    secrets:
      - cert.pem
      - key.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname==explodinator-vm]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  backend:
    driver: overlay
