version: "3.3"

secrets:
  cert.pem:
    file: ./nginx/cert.pem
  key.pem:
    file: ./nginx/key.pem
  aws_creds:
    file: ~/.aws/credentials

services:
  explodinator-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    secrets:
      - aws_creds
    ports:
      - "8080"
  explodinator-proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    secrets:
      - cert.pem
      - key.pem
    links:
      - explodinator-api
    ports:
      - "443:443"
